spring:
  application.name: resource_server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 1200000
      maximum-pool-size: 5
      minimum-idle: 2
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: NgocLe*2004
  jackson:
    date-format: MMMM dd yyyy / HH:mm
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    host_address: host_address
    username: username
    password: password
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
    protocol: smtp
  mvc:
    throw-exception-if-no-handler-found: true

security:
  public-pattern: /api/public/**
  auth:
    username: user_name
    url: http://localhost:8081/oauth/check_token
    client_id: client_id
    client_password: client_password
    connection_timeout: 60
    read_timeout: 60
    whitelist: >
      /,
      /v2/api-docs,
      /swagger-resources,
      /swagger-resources/**,
      /configuration/ui,
      /configuration/security,
      /swagger-ui.html,
      /webjars/**,
      /api/public/**

swagger:
  host:
    address: localhost:8080
    path: /
  api:
    name: Ecommerce Api Documentation
    version: v1
  contact:
    name: Nguyen Le
    url: somr url
    email: nguyenle.workspace@gmail.com
